# Generated by Django 6.0.5 on 2026-09-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(blank=True, max_length=500, upload_to='products/'),
        ),
    ]
